# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Matthew Sherman
description: "Hello. My name is Matthew, and I am a data scientist. My portfolio focuses on interesting projects I have recently undertaken, with a strong emphasis on business impact. Please visit my Github and LinkedIn pages (or download my résumé) by using the links below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Culver City, CA"
resume_url: /docs/Matthew Sherman Resume June 2026.docx
avatar_image: /img/GitHub Profile Pic Square.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/in/matthew-sherman-8954b8117/"
github: "https://github.com/ShermanMatthew"

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

